### ISSUE TITLE
More tags and multiworld support?

### ISSUE THREAD

**Issue by lightyisreal** [Inaayat04/ScoreTag#1]
You should add more tags and the multiworld support

{health} - Show player's health
{max_health} - Show player's max health

**Comment by Inaayat04** [comment]
More tag will add on the next update!.
Make sure to rate the plugin on poggit.

**Comment by lightyisreal** [comment]
> More tag will add on the next update!.
> Make sure to rate the plugin on poggit.
Ok

**Comment by Inaayat04** [comment]
add my discord and tell me the tags i should add.
discord: Unkn0wn#9288

**Comment by Inaayat04** [comment]
Next update more tag will come!.
